default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
   <<: *default
   database: tennis-finder
   username: <%= Rails.application.secrets[:db_user] %>
   host: 127.0.0.1
   port: 3306

test:
   <<: *default
   database: tennis-finder_test

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: root
  database: testDB
  socket:  /cloudsql/rails-test-199116:us-central1:test-db